library(dplyr)
car_df <- read.csv(file='MechaCar_mpg.csv', check.names=F, stringsAsFactors = F)
summary(lm(mpg ~ vehicle_length + vehicle_weight + spoiler_angle + ground_clearance + AWD, data = car_df))
susp_coils <- read.csv(file = 'Suspension_Coil.csv', check.names=F, stringsAsFactors=F)
total_summary <- susp_coils %>% summarize(Mean = mean(PSI), Median = median(PSI), Variance = sd(PSI)**2, SD = sd(PSI))
lot_summary <- susp_coils %>% group_by(Manufacturing_Lot) %>% summarize(Mean = mean(PSI), Median = median(PSI), Variance = sd(PSI)**2, SD = sd(PSI))
t.test(log10(susp_coils$PSI),mu=mean(log10(total_summary$Mean)))
lot_one = subset(susp_coils, Manufacturing_Lot=="Lot1")
lot_two = subset(susp_coils, Manufacturing_Lot=="Lot2")
lot_three = subset(susp_coils, Manufacturing_Lot=="Lot3")
t.test(log10(lot_one$PSI),mu=mean(log10(total_summary$Mean)))
t.test(log10(lot_two$PSI),mu=mean(log10(total_summary$Mean)))
t.test(log10(lot_three$PSI),mu=mean(log10(total_summary$Mean)))
